menu:
    Home: /
    Archive: /archives/
    GitHub: https://github.com/eneim
    Rss: /atom.xml

favicon: /img/eneim.ico
logo: /img/avatar.jpg

# Comment
# e.g disqus: seansun
disqus: eneim

# Analytics
# google-analytics:
ga: 'UA-72567780-7'

# Copyright Infomation
startyear: 2016
